project/blog_project/urls.py
from django.conf.urls import url

from blog_project import views

app_name = 'blog_project'
urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),

    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),

    url(r'category/(?P<pk>[0-9]+)/$', views.category, name='category'),

    url(r'tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),

    url(r'search/', views.search, name='search'),

    url(r'login/', views.login, name='login'),

    url(r'register/', views.register, name='register'),

    url(r'quit/', views.quit, name='quit'),

    url(r'^upload/', views.upload, name='upload'),

    url(r'^abort/', views.abort, name='abort'),
]

project/comments/urls.py
from django.conf.urls import url

from comments import views

app_name = 'comments'

urlpatterns = [

    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog_project.urls', namespace='blog_project')),
    url(r'', include('comments.urls', namespace='comments'))
]

project/comments/models.py
from django.db import models

# 创建评论的模型
from tinymce.models import HTMLField


class Comment(models.Model):

    reader = models.ForeignKey('blog_project.Reader')

    text = HTMLField(null=True)
    # 创建评论的时间，默认成递增
    created_time = models.DateTimeField(auto_now_add=True)
    # 一篇文章会有多条评论，一对多关系
    post = models.ForeignKey('blog_project.Post')

    def __str__(self):
        return self.text[:20]
    class Meta:
        db_table = 'comments'

project/templates/abort.html
{% extends 'base.html' %}
{% block main %}
    <div>
    <ul class="about">
        <p>LY，男，90后python开发工程师！16年入行。一直喜欢web前端及后端技术，一边工作一边积累经验，分享一些个人博客<br />
           <br />
           那脑袋里的智慧，就像打火石里的火花一样，不去打它是不肯出来的。<br />
            <br />
            生命是一出傻子写的戏剧，充满了喧哗与骚动，却找不到一丝意义。<br />
            <br />
            行动的是非曲直，只有从事实的发展上去判断。<br />
            <br />
            什么都比不上厄运更能磨炼人的德性。<br /><span style="float:right">--《莎士比亚》</span>
            <br />
            <img src="../static/base/img/zd01.jpg">
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.leiy.xyz 创建于2018年&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：豫ICP备18028514</p>

    </ul>
</div>
{% endblock main %}

project/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
{% load blog_tags %}

<html>
<head>
    <title>个人博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'base/css/m.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/info.css' %}">
    {% block link %}{% endblock link %}
    <!-- js -->
    <script src="{% static 'base/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/pace.min.js' %}"></script>
    <script src="{% static 'base/js/modernizr.js' %}"></script>


</head>


<body>
    <header>
        <div class="logo">
            <a href="{% url 'blog_project:index' %}">Ly&个人博客</a>
        </div>

        <nav id="nav">
            <ul>
              <li><a href="{% url 'blog_project:index' %}">网站首页</a></li>
              <li><a href="{% url 'blog_project:index' %}">我的相册</a></li>
              <li><a href="{% url 'blog_project:index' %}">我的日记</a></li>
              <li><a href="{% url 'blog_project:abort' %}">关于我</a></li>
              <li><a href="{% url 'blog_project:index' %}">留言</a></li>
              <li><a href="{% url 'blog_project:index' %}">内容页</a></li>
              <li><a href="{% url 'blog_project:index' %}">暂未开放</a></li>
            </ul>
        </nav>
      <script>
        window.onload = function ()
        {
        var obj=null;
        var As=document.getElementById('nav').getElementsByTagName('a');
        obj = As[0];
        for(i=1;i<As.length;i++){if(window.location.href.indexOf(As[i].href)>=0)
        obj=As[i];}
        obj.id='selected'
        }
      </script>
    </header>

<article>
    <div class="l_box">

        <div class="search">
          <form role="search" action="{% url 'blog_project:search' %}" method="get" name="searchform" id="searchform">
              {% csrf_token %}
            <input name="q" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
            <input name="show" value="title" type="hidden">
            <input name="tempid" value="1" type="hidden">
            <input name="tbname" value="news" type="hidden">
            <input name="Submit" class="input_submit" value="搜索" type="submit">
          </form>
        </div>


        <div class="fenlei">
            <h2 >文章分类</h2>
            {% get_categories as category_list %}
            <ul>
                {% for category in category_list %}
                <li>
                    <a href="{% url 'blog_project:category' category.pk %}">
                        {{ category.name }}(<span class="post-count">{{ category.num_posts}}</span>)
                    </a>
                </li>
                {% empty %}
                暂无分类！
                {% endfor %}
            </ul>
        </div>

        <div class="tuijian">
            <h2>最新文章</h2>
            {% get_recent_posts as recent_post_list %}
            <ul>
                {% for post in recent_post_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
                {% empty %}
                暂无文章！
                {% endfor %}
            </ul>
        </div>

        <div class="cloud">
            <h2>标签云</h2>
            {% get_tags as tag_list %}
            <ul>
               {% for tag in tag_list %}
                    <a href="{% url 'blog_project:tag' tag.pk %}">{{ tag.name }}</a>
               {% empty %}
                暂无标签！
               {% endfor %}
            </ul>
        </div>

        <div class="guanzhu">
          <h2>关注我</h2>
          <ul>
            <img src="/static/base/img/wx.png">
          </ul>
        </div>
    </div>



<div class="r_box">
    {% block main %}
    {% endblock main %}
</div>

</article>
<footer>
    <p class="copyright">&copy Design by Ly&个人博客 豫ICP备18028514</p>
</footer>


<script src="{% static 'base/js/script.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

project/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    {% if key %}
        <p>{{ key }}</p>
    {% endif %}
    {% for post in post_list %}
        <li><i><a href="/"><img src="/static/base/img/1.jpg"></a></i>
            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
            <p>{{ post.body|truncatechars:100 }}</p>
            <div class="autor">
                <span class="lm f_l"><a href="/">Ly&个人博客</a></span>
                <span class="dtime f_l">2014-02-19</span>
                <span class="viewnum f_l">浏览（<a href="/">{{ post.views }}</a>）</span>
                <span class="pingl f_l">评论（<a href="/">{{ post.comment_set.count }}</a>）</span>
                <span class="f_r"><a href="{{ post.get_absolute_url }}" class="more">阅读原文</a></span>
            </div>
        </li>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock %}

project/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="infosbox">
        <div class="newsview">
            <h3 class="news_title">{{ post.title }}</h3>
            <div class="bloginfo">
                <ul>
                  <li class="author">作者：<a href="/">LY</a></li>
                  <li class="lmname"><a href="/">{{ post.category.name }}</a></li>
                  <li class="timer">时间：{{ post.created_time }}</li>
                  <li class="view">{{ post.views }}人已阅读</li>
                  <li class="comments-link">{{ post.comment_set.count }}人已评论</li>
                </ul>
              </div>

            <div class="news_con">
                    {{ post.body|safe }}
            </div>
        </div>

        <div class="news_pl">
            <h2>文章评论</h2>

            <div id="login">
                {% if login_user %}
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post">
                        {% csrf_token %}

                        <label>
                            <textarea name="text"></textarea>
                        </label>
                        <br>

                        <input type="submit" value="提交评论" class="btn btn-default">

                    </form>
                {% else %}
                    <span>请登录后，在评论！</span><br>
                    <button class="btn btn-primary" ><a href="{% url 'blog_project:login' %}">登录</a></button>
                {% endif %}
            </div>

            <div class="comment-list-panel" >
                <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                <div class="infosbox">
                    {% for comment in comment_list %}
                    <div class="autor">
                        <span><img class="img-circle" src="{{ comment.reader.photo}}" style="border-radius: 50%; width: 50px;height: 50px"></span>
                        <span class="comment_photo">{{ comment.reader.username }}</span>
                        <span class="comment_data">{{ comment.created_time }}</span>
                    </div>
                    <div class="text">
                        {{ comment.text|safe }}
                    </div>
                    {% empty %}
                    快来抢沙发！python
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':550,
            'height':300
        })
    </script>
{% endblock main %}

project/templates/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in posts %}
        <li><i><a href="/"><img src="/static/base/img/1.jpg"></a></i>
            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
            <p>{{ post.body|truncatechars:100 }}</p>
            <div class="autor">
                <span class="lm f_l"><a href="/">Ly&个人博客</a></span>
                <span class="dtime f_l">{{ post.created_time }}</span>
                <span class="viewnum f_l">浏览（<a href="/">{{ post.views }}</a>）</span>
                <span class="pingl f_l">评论（<a href="/">{{ post.comment_set.count }}</a>）</span>
                <span class="f_r"><a href="{{ post.get_absolute_url }}" class="more">阅读原文</a></span>
            </div>
        </li>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    <div class="pagelist">
     <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
        {% if posts.has_previous %}
        <a class="allpage" href="?page={{ posts.previous_page_number }}">上一页</a>
        {% endif %}
         <!-- 显示当前页面信息 -->
        <a class="allpage">第 {{ posts.number }} 页 / 共 {{ posts.paginator.num_pages }} 页</a>
         <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">下一页</a>
        {% endif %}
    </div>
{% endblock main %}

project/templates/login.html
{% extends 'base.html' %}

{% block main %}
       <div class="infosbox" align="center" style="width:500px;height: 300px ">
            <form action="{% url 'blog_project:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label style="line-height: 100px;">用户名：</label>
                    <input  name="username" type="text" placeholder="请输入用户名" style="height: 30px">
                </div>
                <div class="form-group">
                    <label>密码：</label>
                    <input name="pwd" type="password" placeholder="请输入密码"  style="height: 30px">
                </div>
                <button type="submit" >Login</button>
                <button><a href="{% url 'blog_project:register' %}">Register</a></button>

                <div class="form-group">
                    {% if error_msg %}
                        <span class="col-md-7 text-right" style="color: red;">{{ error_msg }}</span>
                    {% endif %}
                </div>
            </form>
       </div>
{% endblock %}

project/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div class="infosbox" align="center" style="width:600px;height: 500px ">
        <form method="post" action="{% url 'blog_project:register' %}">
            {% csrf_token %}

            <input type="hidden" name="photo" value="{{ form.photo.value }}">

            <div class="form-group">
                <label style="line-height: 50px;">用户名:</label>
                <input style="height: 20px" class="form-control" name="username" value="{{ form.username.value }}">
            </div>

            <div class="form-group">
                <label style="line-height: 50px;">密码:</label>
                <input  style="height: 20px" class="form-control" name="password" type="password">
            </div>


            <div class="form-group">
                <label style="line-height: 50px;">电话:</label>
                <input style="height: 20px" class="form-control" name="phone" value="{{ form.phone.value }}">
            </div>

             <div class="form-group">
                    <label >头像:</label>
                    <img id="preImg"
                         src="{{ form.photo.value|default:'/static/users/default_photo.gif' }}"
                         width="100px" height="120px"
                         onclick="selectImage.click()" style="width: 100px; height: 100px;">
            </div>

            <div class="form-group">
                <div  style="line-height: 50px;">
                    <button class="btn btn-primary" style="width: 50px">注册</button>
                    <a class="btn btn-link" href="{% url 'blog_project:login' %}">已注册用户，去登录</a>
                </div>
            </div>
        </form>
    </div>
    <input type="file"
           id="selectImage"
           style="display: none;"
           onchange="uploadImage(this.files[0])">
{% endblock main %}
{% block js %}
<script>
    function uploadImage(imgFile) {
        alert("正在上传图片： "+imgFile.name);
        var url = '/upload/';  //上传图片的路径(接口)
        var fd = new FormData();  // 将上传的文件封装到FormData中
        fd.append('u_img', imgFile);

        var xhr = new XMLHttpRequest();
        xhr.open('POST', url, true);  //打开接口（连接）

        // 设置请求监听(成功，或失败)
        xhr.onload = function (ev) {
            // 判断请求是否成功
            if(xhr.status == 200 && xhr.readyState==4){
                alert(xhr.responseText);  //打印响应的文本数据
                // 将响应的json文本转成json对象
                data = JSON.parse(xhr.responseText);

                // 显示上传的图片
                $('#preImg').attr('src', data.path);

                //将上传图片的路径写入到注册表单中
                $('input[name="photo"]').val(data.path);

            }
        }

        // 发送数据
        xhr.send(fd);


    }
</script>
{% endblock %}